# Generated by Django 2.2.2 on 2020-02-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('plane', models.CharField(max_length=50)),
                ('depature_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('passport_data', models.CharField(max_length=1000)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=500)),
                ('aircompany', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Aircompany')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('price', models.PositiveIntegerField()),
                ('is_busy', models.BooleanField(default=False)),
                ('departure', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Departure')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SeatType')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircompany', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Aircompany')),
                ('departure_point', models.ForeignKey(default='default_from', on_delete=django.db.models.deletion.CASCADE, related_name='Airport.name+', to='mainapp.Airport')),
                ('to', models.ForeignKey(default='default_to', on_delete=django.db.models.deletion.CASCADE, related_name='Airport.name+', to='mainapp.Airport')),
            ],
        ),
        migrations.AddField(
            model_name='departure',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Flight'),
        ),
    ]
