# Generated by Django 2.2.2 on 2020-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
        migrations.AlterField(
            model_name='aircompany',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
