# Generated by Django 2.2.2 on 2020-01-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200117_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='depature',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Flight'),
        ),
    ]
