# Generated by Django 2.2.2 on 2020-01-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200122_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depature',
            name='number_of_seats',
        ),
        migrations.AddField(
            model_name='seattype',
            name='aircompany',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Aircompany'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircompany',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Aircompany'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
