# Generated by Django 2.2.2 on 2020-01-24 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200124_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person'),
        ),
    ]
