# Generated by Django 2.2.2 on 2020-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200124_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircompany',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
