# Generated by Django 2.2.2 on 2020-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('departure', models.CharField(max_length=3)),
                ('arrival', models.CharField(max_length=3)),
                ('date', models.DateField()),
            ],
        ),
    ]
