# Generated by Django 2.2.2 on 2020-02-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
            ],
        ),
    ]
